apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
spec:
  selector:
    app: result
  ports:
    - name: "result-service"
      port: 80
      targetPort: 80
      nodeport: 30081
  type: NodePort